language: perl
perl:
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"

before_install:
  cpanm -n Devel::Cover::Report::Coveralls XML::OPML::SimpleGen
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
